import streamlit as st
import sqlite3
import datetime
import pandas as pd
import speech_recognition as sr
import io
import os
import time
from streamlit_mic_recorder import mic_recorder
from pydub import AudioSegment
from gtts import gTTS
from streamlit_gsheets import GSheetsConnection
# PDF Library
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

st.set_page_config(page_title="Nia Rice Mill AI", page_icon="🌾", layout="wide")

try:
    conn_gsheets = st.connection("gsheets", type=GSheetsConnection)
except:
    st.error("⚠️ Internet Error.")
    st.stop()

if 'logged_in' not in st.session_state:
    st.session_state.logged_in = False
if 'user_info' not in st.session_state:
    st.session_state.user_info = {}
if 'step' not in st.session_state:
    st.session_state.step = 1
if 'pending_weight' not in st.session_state:
    st.session_state.pending_weight = None
if 'last_receipt' not in st.session_state:
    st.session_state.last_receipt = None # Parchi save karne ke liye

def speak(text):
    try:
        tts = gTTS(text=text, lang='hi')
        tts.save("temp.mp3")
        st.audio("temp.mp3", format="audio/mp3", autoplay=True)
    except:
        pass

# --- NEW: PDF GENERATOR FUNCTION ---
def create_pdf(mill_id, date, time_str, weight, rate, price, munim_name):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Box Border
    c.setStrokeColor(colors.black)
    c.setLineWidth(2)
    c.rect(50, height - 350, width - 100, 300) # Box size

    # Header
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 100, f"{mill_id}")
    
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 125, "OFFICIAL WEIGHING RECEIPT")
    
    c.setLineWidth(1)
    c.line(60, height - 135, width - 60, height - 135) # Line

    # Details
    y = height - 170
    x_left = 100
    x_right = 350
    
    c.setFont("Helvetica", 14)
    c.drawString(x_left, y, f"Date: {date}")
    c.drawString(x_right, y, f"Time: {time_str}")
    y -= 30
    
    c.drawString(x_left, y, f"Operator: {munim_name}")
    y -= 40 # Thoda gap
    
    # Main Data (Bada Dikhega)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(x_left, y, "Weight (Wazan):")
    c.drawString(x_right, y, f"{weight} kg")
    y -= 30
    
    c.setFont("Helvetica", 14)
    c.drawString(x_left, y, f"Rate:")
    c.drawString(x_right, y, f"Rs {rate}/qt")
    y -= 40
    
    # Total Amount
    c.setFont("Helvetica-Bold", 22)
    c.drawString(x_left, y, "TOTAL AMOUNT:")
    c.drawString(x_right, y, f"Rs {price:,.2f}")
    
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, height - 330, "Generated by Nia Rice Mill SaaS | Digital India")

    c.save()
    buffer.seek(0)
    return buffer

# --- ACTIVATION ---
def activate_account(mill_id, secret_code, new_user, new_pass, name):
    try:
        df = conn_gsheets.read(worksheet="Users")
        df.columns = df.columns.str.strip()
        if 'Secret_Code' not in df.columns and 'Secret_Cod' in df.columns:
            df.rename(columns={'Secret_Cod': 'Secret_Code'}, inplace=True)
        
        df['Mill_ID'] = df['Mill_ID'].astype(str).str.strip()
        df['Secret_Code'] = df['Secret_Code'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
        
        input_mill = str(mill_id).strip()
        input_code = str(secret_code).strip()
        
        mask = (df['Mill_ID'] == input_mill) & (df['Secret_Code'] == input_code)
        
        if df[mask].empty: return "INVALID_CODE"
        
        row_index = df[mask].index[0]
        current_user = str(df.at[row_index, 'Username'])
        if current_user != "nan" and current_user.strip() != "": return "ALREADY_REGISTERED"
            
        df.at[row_index, 'Username'] = new_user
        df.at[row_index, 'Password'] = new_pass
        df.at[row_index, 'Name'] = name
        df.at[row_index, 'Is_Active'] = "TRUE"
        
        conn_gsheets.update(worksheet="Users", data=df)
        return "SUCCESS"
    except Exception as e: return f"Error: {str(e)}"

# --- LOGIN ---
def check_login(username, password):
    try:
        users_df = conn_gsheets.read(worksheet="Users")
        users_df.columns = users_df.columns.str.strip()
        users_df['Username'] = users_df['Username'].astype(str).str.strip()
        user = users_df[users_df['Username'] == str(username).strip()]
        if not user.empty:
            stored_pass = str(user.iloc[0]['Password']).strip()
            status = str(user.iloc[0]['Is_Active']).strip().upper()
            if str(password).strip() == stored_pass:
                if status in ['TRUE', '1', '1.0', 'YES', 'ON']: return user.iloc[0].to_dict()
                else: return "BLOCKED"
        return None
    except: return None

# --- SAVE DATA ---
def save_data_secure(wazan, rate):
    now = datetime.datetime.now()
    d_date = now.strftime("%Y-%m-%d")
    d_time = now.strftime("%H:%M:%S")
    my_mill_id = st.session_state.user_info['Mill_ID']
    munim = st.session_state.user_info['Name']
    price = (wazan / 100.0) * rate

    # Local DB
    try:
        conn = sqlite3.connect('rice_mill.db')
        conn.execute('INSERT INTO records (date, time, weight, price, mill_id) VALUES (?, ?, ?, ?, ?)', 
                  (d_date, d_time, wazan, price, my_mill_id))
        conn.commit()
        conn.close()
    except: pass

    # Google Sheets
    try:
        new_data = pd.DataFrame([[my_mill_id, d_date, d_time, wazan, price, munim]], 
            columns=['Mill_ID', 'Date', 'Time', 'Weight', 'Price', 'EntryBy'])
        existing = conn_gsheets.read() 
        updated = pd.concat([existing, new_data], ignore_index=True)
        conn_gsheets.update(data=updated)
        
        # --- GENERATE PDF RECEIPT ---
        pdf_file = create_pdf(my_mill_id, d_date, d_time, wazan, rate, price, munim)
        return pdf_file # Return PDF object
    except: return None

# ==========================================
# UI STARTS
# ==========================================
if not st.session_state.logged_in:
    st.markdown("<h1 style='text-align: center;'>🌾 Nia Rice Mill SaaS</h1>", unsafe_allow_html=True)
    tab1, tab2 = st.tabs(["🔑 Login", "✨ Activate"])
    with tab1:
        with st.form("login"):
            u = st.text_input("Username")
            p = st.text_input("Password", type="password")
            if st.form_submit_button("Login", type="primary"):
                res = check_login(u, p)
                if res == "BLOCKED": st.error("Blocked")
                elif res:
                    st.session_state.logged_in = True
                    st.session_state.user_info = res
                    st.session_state.current_rate = 2500.0
                    st.rerun()
                else: st.error("Invalid")
    with tab2:
        ac1, ac2 = st.columns(2)
        with ac1:
            aid = st.text_input("Mill ID")
            acode = st.text_input("Secret Code", type="password")
        with ac2:
            nu = st.text_input("User")
            np = st.text_input("Pass", type="password")
            nn = st.text_input("Name")
        if st.button("Activate"):
            st.info(activate_account(aid, acode, nu, np, nn))
    st.stop()

# DASHBOARD
st.markdown(f"### 🏭 {st.session_state.user_info['Mill_ID']} | 👤 {st.session_state.user_info['Name']}")
if st.sidebar.button("Logout"):
    st.session_state.logged_in = False
    st.rerun()
st.divider()

c1, c2 = st.columns([1, 2])
with c1:
    st.subheader("🎙️ Entry")
    # Step 1: Record
    if st.session_state.step == 1:
        audio = mic_recorder(start_prompt="🔴 Speak", stop_prompt="⏹️ Stop", key='rec1')
        if audio:
            try:
                webm = audio['bytes']
                sound = AudioSegment.from_file(io.BytesIO(webm))
                wav = io.BytesIO()
                sound.export(wav, format="wav")
                wav.seek(0)
                r = sr.Recognizer()
                with sr.AudioFile(wav) as source:
                    txt = r.recognize_google(r.record(source), language="hi-IN")
                    nums = [float(s) for s in txt.split() if s.replace('.', '', 1).isdigit()]
                    if nums:
                        st.session_state.pending_weight = nums[0]
                        st.session_state.step = 2
                        st.rerun()
            except: pass
            
    # Step 2: Confirm
    elif st.session_state.step == 2:
        w = st.session_state.pending_weight
        st.success(f"⚖️ {w} kg")
        if st.button("✅ SAVE & PRINT"):
            pdf_data = save_data_secure(w, st.session_state.current_rate)
            if pdf_data:
                st.session_state.last_receipt = pdf_data
                st.session_state.step = 3 # Go to Receipt view
                st.rerun()
        if st.button("❌ CANCEL"):
            st.session_state.step = 1
            st.rerun()
            
    # Step 3: Receipt Download
    elif st.session_state.step == 3:
        st.balloons()
        st.success("✅ Entry Saved!")
        st.markdown("### 📄 Digital Parchi Taiyar Hai")
        
        # Download Button
        st.download_button(
            label="⬇️ Download Receipt (PDF)",
            data=st.session_state.last_receipt,
            file_name=f"receipt_{datetime.datetime.now().strftime('%H%M%S')}.pdf",
            mime="application/pdf",
            type="primary"
        )
        
        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("🔙 New Entry"):
            st.session_state.step = 1
            st.rerun()

with c2:
    st.subheader("📊 Live Entries")
    try:
        df = conn_gsheets.read()
        my_df = df[df['Mill_ID'] == st.session_state.user_info['Mill_ID']]
        st.dataframe(my_df.tail(5), hide_index=True)
    except: pass
